# Generated by Django 2.2 on 2020-10-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuenteDeDatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fuenteDeDatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuenteDeDatos.FuenteDeDatos')),
            ],
        ),
    ]
