# Generated by Django 2.2 on 2020-10-01 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteDeDatos',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('estadisticas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estadisticas.Estadisticas')),
            ],
        ),
    ]
